[package]
name = "cfl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5", features = ["derive"] }
clipboard = "0.5.0"
glob = "0.3.1"
ignore = "0.4.23"
tempfile = "3.14.0"
thiserror = "2.0.6"
